name: Matrix Strategy Composed Action

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ 'dev', 'prod', 'ro-prod', 'staging' ]
    environment: ${{ matrix.environment }}
    steps:
      - name: Matrix run
        uses: TheProjectAurora/demo-composite-action/.github/actions/matrix-action@main
        with:
          environment: ${{ matrix.environment }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
