name: Debugging Action

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest    
    steps:
      - name: Matrix run
        run: |
            echo "The github context is:" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat <<EOF  >> $GITHUB_STEP_SUMMARY
            ${{ toJson(github) }}
            EOF
            echo '```' >> $GITHUB_STEP_SUMMARY