name: Debugging Action

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: GitHub context
        run: |
            echo "The github context is:" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat <<EOF  >> $GITHUB_STEP_SUMMARY
            ${{ toJson(github) }}
            EOF
            echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Env context
        run: |
            echo "The env context is:" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat <<EOF  >> $GITHUB_STEP_SUMMARY
            ${{ toJson(env) }}
            EOF
            echo '```' >> $GITHUB_STEP_SUMMARY  