name: Matrix Strategy Shared Workflow

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12, 14, 16]
    steps:
      - name: Hello World
        run: echo "Hello, World from ${{ matrix.os }} with Node.js ${{ matrix.node }}!"